version: '3.8'

services:
  nuxt-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - RESEND_API_KEY=${RESEND_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
