# AWS ECS Deployment
version: '3.8'
services:
  nuxt-app:
    image: ghcr.io/hamantuan/nuxt3base:latest
    ports:
      - "80:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
